# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: user
    password:

# JPA
  jpa:
    hibernate:
      ddl-auto: create-drop

# Swagger Setting
springdoc:
  swagger-ui:
    path: /api-doc
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8